# Generated by Django 2.0.2 on 2018-02-03 17:16

from django.db import migrations


def create_initial_books(apps, schema_editor):
    Book = apps.get_model("green", "Book")
    Book.objects.create(name="Winnie The Pooh", has_leather_binding=True)
    Book.objects.create(name="Ender's Game", has_leather_binding=False)


class Migration(migrations.Migration):
    dependencies = [
        ('green', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_books, migrations.RunPython.noop)
    ]
