# Generated by Django 2.0.2 on 2018-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='has_leather_binding',
        ),
    ]
